### ISSUE TITLE
Is BBC Working?

### ISSUE THREAD

**Issue by uckthis** [denobisipsis/adownloader#114]
Hello,
BBC has never worked for me using VPN, and so I always used Online Proxies option to download from BBC. Recently it has stopped working, so I don't know if it's the proxies or module that is not working. Please check and fix.
Thank you.

**Comment by denobisipsis** [comment]
fixed

**Comment by uckthis** [comment]
Sorry, but still doesn't work for me. Maybe the issue is on my end.
